// Generated by scripts/vendor_highs.py; Apple static, MIT configuration.
#ifndef HCONFIG_H_
#define HCONFIG_H_
#define FAST_BUILD
#define CUPDLP_CPU
#define HIGHS_NO_DEFAULT_THREADS
#define HIGHS_HAVE_BUILTIN_CLZ
#define HIGHS_GITHASH "04024d701f79feb8e2f18bc3df0dffc04ef05088+upstream-3177-3179-3181"
#define HIGHS_VERSION_MAJOR 1
#define HIGHS_VERSION_MINOR 15
#define HIGHS_VERSION_PATCH 1
#endif
